%%writefile render.yaml
services:
  - type: web
    name: mp4-to-mp3-api
    env: python
    buildCommand: "apt-get install -y ffmpeg && pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    plan: free
